// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Piece } from "./Piece";

export interface Board { squares: Array<Array<Piece>>, turn: number, }